### ISSUE TITLE
Cannot create FB

### ISSUE THREAD

**Issue by SlimeDog** [Huskehhh/FakeBlock#11]
Spigot 1.15.2 (Jenkins 2623)
FakeBlock 1.7

Execute in-game
> fb create xyzzy

There is no feedback in-game or at console, and nothing is recorded.

Related issue:
If I click the corners with AIR (ie., empty hand), multiple errors are generated. Is right-click with AIR supported -- ie., not null?

If I click with a stick, there are no errors, but still no feedback or recorded data.

I expect that this is due to recent Spigot changes.

**Comment by Huskehhh** [comment]
Hey man! Cheers for the report. Currently on holidays but if I get a chance I'll have a look

**Comment by Huskehhh** [comment]
Hey. Some more information!

This happens due to 1.7 now requiring a material to be given upon creation!
```/fb create xyzzy TNT```

The feedback should have been indicating the wrong amount of arguments, and [has now been adjusted](https://github.com/Huskehhh/FakeBlock/commit/92af503805e23fd28aa183e6454a595e590286b7#diff-f8fd6343869dc816ff0ddada0cbb21c1R92)

Thanks again for your continued contributions 👍 I really appreciate it!

**Comment by SlimeDog** [comment]
Thanks. I hope to get some testing in this weekend.
